### ISSUE TITLE
Duda para crear script para habilitar y deshabilitar las sims por separado

### ISSUE THREAD

**Issue by ortegafernando** [bq/aquaris-E5-4G#1]
Desde soporte tecnico de BQ me han dicho que aqui puedo preguntar sobre lo indicado en este post del foro.

http://www.mibqyyo.com/comunidad/discussion/comment/421672#Comment_421672

Alguien me puede ayudar ? 

Gracias

**Comment by Kra1o5** [comment]
Hola @ortegafernando ,

Estas son las fuentes del kernel para el dispositivo y no tienen relación con tu petición.

Para tu consulta seria mejor que la realizases a través del email opensource@bq.com

Un saludo
